language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - rustup component add clippy

script:
  - cargo build --verbose
  - cargo clippy -- -D clippy::all
  - cargo test --verbose
