[package]
name = "editor"
version = "0.1.0"
authors = ["Shane Logsdon <shane@shanelogsdon.com>"]
edition = "2018"
license = "MIT"

[dependencies]
async-std = "1.4"
crossterm = { version = "0.14", features = ["event-stream"] }
futures = "0.3"

[[bin]]
name = "editor"
path = "src/bin/main.rs"
